# User Login Credentials
login:
  email: "saravan@ilife.tech"
  password: "$@ravan123"

# SMTP Configuration (Sensitive Data)
smtp:
  server: "smtp.sendgrid.net"
  port: 587
  username: "saravan@ilife.tech"
  password: "your_smtp_password"
